config/routes.rb
Rails.application.routes.draw do
  get "blogs/search"

  root "blogs#index"

  resources :blogs do
  	get 'pdf', to: "blogs#get_pdf"
  	get 'csv' ,  to: "blogs#get_csv"
  	resources :comments , only: [:create]
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
	validates :title,:author,:content , presence: true
	validates :content , length: { maximum: 10000, minimum: 10 }

	has_many :comments, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog

  validates :content,:writter, presence: true
  validates :content, length: { minimum: 10 , maximum: 150 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
require "csv"

class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]


  def index
    @blogs = Blog.all.order("created_at desc")
  end

  def show
  end

  def new
    @blog = Blog.new
  end

  def edit
  end

  def create
    @blog = Blog.new(blog_params)

      if @blog.save
         redirect_to @blog, notice: 'Blog was successfully created.' 
      else
        render :new 
      end

  end

  def update
  
      if @blog.update(blog_params)
        redirect_to @blog, notice: 'Blog was successfully updated.' 
      else
        render :edit 
      end
  end

  def destroy
    if @blog.destroy
      redirect_to blogs_url, notice: 'Blog was successfully destroyed.' 
    end
  end

  def search

    key = Regexp.new(params[:search],"i")
    @result = []
    Blog.all.each do |blog|
      if blog.title.match(key) or blog.author.match(key)
        @result<<blog
      end
    end
  end

  def get_pdf
    send_data make_pdf.render,
      filename: "blog_#{@blog.title}.pdf",
      type: 'application/pdf',
      disposition: 'inline'
  end

  def get_csv
    send_data make_csv, filename: "blog_#{@blog.title}_comments.csv"
  end


  private

    def set_blog
      @blog = Blog.find(params[:id])
    end


    def blog_params
      params.require(:blog).permit(:title, :author, :content)
    end

    def make_pdf
      Prawn::Document.new do |pdf|    
        @blog = Blog.find(params[:blog_id])   
        pdf.text <<-STR,:inline_format => true

        <b>Title :</b> #{@blog.title} 

        <b>Author :</b> #{@blog.author} 

        #{@blog.content} 

        STR
      end
    end

    def make_csv

      headings = %w{writter content created_at} 
      @blog = Blog.find(params[:blog_id])
      comments = @blog.comments.order("created_at desc")

      CSV.generate do |csv|
        comments.each do |comment|
          csv << headings.map{ |attr| comment.send(attr) }
        end
      end
      
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


def create
	@comment=Comment.new(comment_params)

	@comment.blog_id = params[:blog_id]

	if @comment.save
		redirect_to request.referrer, notice: "Comment was posted successfully."
	else
		str = "Comment could not be posted due to the following errors: "
		@comment.errors.full_messages.each do |error|
			str+=error + ", "
		end

		redirect_to request.referrer, notice: str
	end
end


private

    def comment_params
      params.require(:comment).permit(:writter, :content)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/views/blogs/_comment_form.html.erb
<%= form_tag(blog_comments_path(@blog),:method=>"post",:class => "comment-form") do%>
	<%= label "writter","Name" %>
	<br>
	<%= text_field_tag "comment[writter]" %> 
	<br>
	<br>
	<%= text_area_tag "comment[content]" , nil ,placeholder: "Write your comment here...", cols: "20", rows: "10" %>
	<br>
	<%= submit_tag  "Post Comment"%>
<% end %>

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title ,class: "form-label" %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :author ,class: "form-label" %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :content ,class: "form-label" %>
    <br>
    <%= form.text_area :content, cols: "50", rows: "30" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/_search_form.html.erb
<%= form_tag("blogs/search",:method => "get") do%>

<%=label :blog,"Search for blogs by title or author name:" %>
<br><br>
<%=text_field_tag :search ,nil,required: true%>
<%=submit_tag "Search !"%>

<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<h1> Simple Blogs ! </h1>

<p id="notice"><%= notice %></p>

<%= render 'search_form' %>

<h3>Blogs: </h3>

<ol>

    <% @blogs.each do |blog| %>

      <li class="blog-posts" >
        <p> <b> <%= blog.title %> </b> written by <%= blog.author %></p>
        <p><%= link_to 'Show', blog %> <%= link_to 'Edit', edit_blog_path(blog) %> <%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %> </p>
        <p>Posted <%= time_ago_in_words(blog.created_at) %></p>
        <br>
      </li>
      

    <% end %>
</ol>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/search.html.erb
<h2> Search results </h2>

<% unless @result.size>0 %>

	<div> There where no matching blogs for your query </div>

<% else %>

	<div> <%= @result.size %> blogs matched your search query </div>

	<ol>
		<% @result.each do |i| %>
			<li> 
				<div> 
			 		<p> <b> Title: </b> <%=i.title %>  </p>
			 		<p> <b> Author: </b> <%=i.author %> </p>
			 		<p> <%= link_to "Visit this blog" , blog_path(i)  %> </p>
				</div>
			</li>
		<% end %>
	</ol>

<% end %>

<%= link_to "Back", blogs_path  %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<div class="show-blog">

<p class="title">
  <span class="title-name"><%= @blog.title %></span> written by <span class="title-author"><%= @blog.author %></span>
</p>

 
 <p class="content"> <%= @blog.content %> </p>

<%= link_to 'Download pdf', blog_pdf_path(@blog) %> |
<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>
</div>


<h2>Comments: </h2>
<div class="comments">

<div class="comments-count"><%= @blog.comments.size %> comments for this blog </div>
<br>
<%= link_to 'Download comments csv', blog_csv_path(@blog) %>
<br>
<%=render "comment_form.html.erb" %>

<% @blog.comments.order("created_at desc").each do |comment| %>

  <div class="comment">

    <div class="comment-author">
      <%= comment.writter %> commented...
    </div>

    <div class="comment-content">
      <%= comment.content %>
    </div>

    <div class="comment-time">
      <%= time_ago_in_words(comment.created_at) %>
    </div>

  </div>

<% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>